### ISSUE TITLE
Make controls' z-index configurable

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-smart-link#11]
### Motivation

It would be great to have z-index CSS property of overlay (border with pencil).

I have my menu with z-index:10002 (inherited from template) , so I would appreciate being able to customize that.

![image](https://user-images.githubusercontent.com/9218736/91619691-167add00-e98e-11ea-8fc7-a75dcb783ea1.png)

### Proposed solution

Make ti a part of [the configuration](https://github.com/Kentico/kontent-smart-link#configuration)

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by dpbeaumont** [comment]
I have the same issue, with a preview bar integrated as recommended. Image below.
![image](https://user-images.githubusercontent.com/49551821/148421122-dad59340-cf60-4df5-9e82-b61878200163.png)

You can see here the `ksl-toolbar` id has styling to set the `z-index` to 10. 
Issue I have is the header has a z-index >10 so the preview bar needs to be >10 but <10 for the tooltip to appear on top.
![image](https://user-images.githubusercontent.com/49551821/148421223-47f05a35-d9ca-4c34-9bf5-5384516459a3.png).

Being able to set this when setting up smart link would be great, potentially in the interface. IDefaultDataAttributes.

**Comment by dpbeaumont** [comment]
A quick fix for this I would propose if possible is could the z-index be defaulted to a value of like 900.  Giving users the opportunity to use values <=899, instead of limiting them to <=9. Then a configurable fix could work as a long-term solution.

**Comment by JanBarton** [comment]
Hey there!
A new version of kontent-smart-link version (`v.2.3.1`) brings up a possibility to customize the z-index for all smart link elements. All you need to do is set the base value with the new custom CSS property called `--ksl-z-index`:
https://github.com/Kentico/kontent-smart-link#customization

**Comment by dpbeaumont** [comment]
Confirmed working, thanks for adding this feature.
